deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: _site
  target-branch: master
  on:
    branch: web-development
language: ruby
rvm:
- 2.3
script: "JEKYLL_ENV=production bundle exec jekyll serve"